name: Update ligo version
on:
  schedule:
    - cron:  "5/10 */1 * * *"
jobs:
  update-version:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update Formula
        run: ./scripts/update-formula.sh

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          add: 'Formula'
          default_author: github_actions
          message: "Update to latest release"
          branch: master

      # steps from brew-test.yml
      - name: Build and test
        run: ./scripts/build-bottle.sh

      - name: Upload bottle to Github Actions
        uses: actions/upload-artifact@v2
        with:
          name: homebrew-bottles
          path: '*.bottle.*'